name: Main Workflow  

on:
  workflow_dispatch:  # Required for Workflow 1 to trigger this workflow

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run post-checkstyle tasks
        run: echo "CI with Checkstyle completed successfully. Now running main workflow."
