name: Main Workflow  

on:
  workflow_run:
    workflows: ["controller.yml"]
    types:
      - completed

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Your main workflow steps go here
      - name: Do something after CI with Checkstyle completes
        run: echo "The CI with Checkstyle workflow has completed successfully, and now the main workflow is triggered."
