name: CI with Checkstyle

on:
  push:
    branches:
      - develop # Trigger on pushes to the controller branch

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2 

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Extract git commit data
      - name: Extract git commit data
        id: commit-data
        uses: rlespinasse/git-commit-data-action@v1.x

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 5: JUnit tests
      - name: Run JUnit tests
        run: mvn test

      # Step 6: Download and run Checkstyle
      - name: Run Checkstyle
        run: |
          CHECKSTYLE_VERSION=8.45
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-$CHECKSTYLE_VERSION/checkstyle-$CHECKSTYLE_VERSION-all.jar -O checkstyle.jar
          java -jar checkstyle.jar -c /google_checks.xml $(find . -name "*.java")

      # Step 7: Raise PR
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "controller"   # Source branch
          base: "develop"        # Target branch for merging
          title: "Demo for auto PR"
          commit-message: "Demo for auto PR [skip ci]"
          committer: "${{ steps.commit-data.outputs.author-name }} <${{ steps.commit-data.outputs.author-email }}>"
          author: "${{ steps.commit-data.outputs.author-name }} <${{ steps.commit-data.outputs.author-email }}>"
          body: "This PR was automatically created after successful CI checks."
          token: ${{ secrets.LONDI }}
          delete-branch: true

      # Step 8: Approve Pull Request
      - name: Approve Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.SG_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}

      # Step 9: Merge Pull Request using squash strategy
      - name: Merge Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.LONDI }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash
